"""Provider-agnostic financial research data access backed by OpenBB."""

from .canonical import (
    AssetIdentity,
    AssetResearchData,
    CanonicalAssetType,
    CompanyFiling,
    CompanyFilings,
    DataQuality,
    EquityQuote,
    FreshnessStatus,
    FundamentalsData,
    MacroSeries,
    PriceSeries,
    ProviderAttempt,
    QualityStatus,
    ResearchProvenance,
)
from .openbb_client import (
    OpenBBResearchClient,
    ResearchConfigurationError,
    ResearchData,
    ResearchEntitlementError,
    ResearchError,
    ResearchInvalidSymbolError,
    ResearchMissingCredentialError,
    ResearchNoDataError,
    ResearchProviderError,
    ResearchProviderSettings,
    ResearchRateLimitError,
    ResearchUnsupportedEndpointError,
)
from .provider_status import ProviderStatus, provider_status_payload, provider_statuses
from .service import CanonicalResearchService
from .serialization import canonical_json, to_jsonable
from .findings import FindingCategory, FindingDirection, FindingEvidence, FindingType, ResearchAnalysis, ResearchFinding
from .relevance import RelevancePolicy, ResearchRelevanceEngine
from .reports import (
    AssetResearchReport,
    ReportDataConfidence,
    ReportDataCoverage,
    ReportDepth,
    ReportFactor,
    ReportMetric,
    ReportRisk,
    ReportSection,
    ReportSource,
    ReportSummary,
)
from .report_service import AssetResearchReportService, ReportPolicy
from .statistical_service import StatisticalPolicy, StatisticalResearchService
from .statistics import (
    BetaResult,
    CorrelationMethod,
    CorrelationResult,
    DistributionResult,
    HypothesisTestResult,
    PercentileResult,
    RegressionResult,
    RegimeComparisonResult,
    RegimeTest,
    ResultStatus,
    ReturnType,
    RollingCorrelationResult,
    StatisticalSeries,
    StatisticalContext,
    VolatilityResult,
    ZScoreResult,
)
from .historical import DrawdownResearchResult, EventStudyResult, HistoricalStatus, RegimeHistoricalResult
from .historical_service import HistoricalResearchPolicy, HistoricalResearchService
from .orchestration import (
    AssetComparison,
    AssetResolution,
    AssetResolver,
    ComparisonDimension,
    ExecutionTrace,
    RequestStatus,
    ResearchAnalysisType,
    ResearchIntent,
    ResearchOrchestrator,
    ResearchPlan,
    ResearchPlanner,
    ResearchRequest,
    ResearchResponse,
    ResearchResponseValidator,
    ResolutionStatus,
    parse_research_question,
    resolve_timeframe,
)

__all__ = [
    "OpenBBResearchClient",
    "CanonicalResearchService",
    "AssetIdentity",
    "AssetResearchData",
    "CanonicalAssetType",
    "CompanyFiling",
    "CompanyFilings",
    "DataQuality",
    "EquityQuote",
    "FreshnessStatus",
    "FundamentalsData",
    "MacroSeries",
    "PriceSeries",
    "ProviderAttempt",
    "QualityStatus",
    "ResearchProvenance",
    "canonical_json",
    "to_jsonable",
    "ResearchConfigurationError",
    "ResearchData",
    "ResearchEntitlementError",
    "ResearchError",
    "ResearchInvalidSymbolError",
    "ResearchMissingCredentialError",
    "ResearchNoDataError",
    "ResearchProviderError",
    "ResearchProviderSettings",
    "ResearchRateLimitError",
    "ResearchUnsupportedEndpointError",
    "ProviderStatus",
    "provider_status_payload",
    "provider_statuses",
    "FindingCategory",
    "FindingDirection",
    "FindingEvidence",
    "FindingType",
    "RelevancePolicy",
    "ResearchAnalysis",
    "ResearchFinding",
    "ResearchRelevanceEngine",
    "AssetResearchReport",
    "AssetResearchReportService",
    "ReportDataConfidence",
    "ReportDataCoverage",
    "ReportDepth",
    "ReportFactor",
    "ReportMetric",
    "ReportPolicy",
    "ReportRisk",
    "ReportSection",
    "ReportSource",
    "ReportSummary",
    "BetaResult",
    "CorrelationMethod",
    "CorrelationResult",
    "DistributionResult",
    "HypothesisTestResult",
    "PercentileResult",
    "RegressionResult",
    "RegimeComparisonResult",
    "RegimeTest",
    "ResultStatus",
    "ReturnType",
    "RollingCorrelationResult",
    "StatisticalPolicy",
    "StatisticalResearchService",
    "StatisticalSeries",
    "StatisticalContext",
    "VolatilityResult",
    "ZScoreResult",
    "DrawdownResearchResult",
    "EventStudyResult",
    "HistoricalResearchPolicy",
    "HistoricalResearchService",
    "HistoricalStatus",
    "RegimeHistoricalResult",
    "AssetComparison",
    "AssetResolution",
    "AssetResolver",
    "ComparisonDimension",
    "ExecutionTrace",
    "RequestStatus",
    "ResearchAnalysisType",
    "ResearchIntent",
    "ResearchOrchestrator",
    "ResearchPlan",
    "ResearchPlanner",
    "ResearchRequest",
    "ResearchResponse",
    "ResearchResponseValidator",
    "ResolutionStatus",
    "parse_research_question",
    "resolve_timeframe",
]
